### ISSUE TITLE
How well goes saga pattern and Kafka together?

### ISSUE THREAD

**Issue by JanRou** [glazkovalex/Rebus.Kafka#10]
Hello, 

Does the saga pattern implemented in Rebus and Kafka go together?

I'm very happy to see that you have coded a transport layer for Kafka. However it's not part of the rebus transports available on rebus github. I've on Stackoverflow found this answer for a question regarding Kafka and the saga pattern: https://stackoverflow.com/a/58748235

I case your answer is yes, please explain the conditions and setup of Rebus. This may be among a lot of other setups Kafka partitions and topics.

Regards
Jan Rou

**Comment by JanRou** [comment]
I found the saga sample! Closed.

**Comment by glazkovalex** [comment]
> Does the saga pattern implemented in Rebus and Kafka go together?

Hello, @JanRou!
In my opinion, Saga and Apache Kafka combine well. There is an [example](https://github.com/glazkovalex/Rebus.Kafka/blob/14e06b88634b9b2b1051026ed808b7f1148bab52/Examples/IdempotentSaga/Program.cs#L49) and a Saga [test](https://github.com/glazkovalex/Rebus.Kafka/blob/14e06b88634b9b2b1051026ed808b7f1148bab52/Rebus.Kafka.Tests/SagaTests.cs) on Rebus.Kafka. And yes, this Kafka transport for Rebus is unofficial. Something may not work. If you find a bug or suggestions appear, then write!
