### ISSUE TITLE
Does it work with the Rebus Outbox

### ISSUE THREAD

**Issue by esskar** [glazkovalex/Rebus.Kafka#11]
Hello,

looking for a messaging solution that supports kafka and outbox. Is this the right addon?

Thanks.

**Comment by glazkovalex** [comment]
Hellow!
The Outbox pattern is very simple and does not involve any special "solutions" or "right addon" to implement it.
[Rebus.Kafka](https://github.com/glazkovalex/Rebus.Kafka ) this is just an implementation of the Apache Kafka transport for the [Rebus](https://github.com/rebus-org/Rebus ) bus, which **contains some [implementation of the Outbox pattern](https://github.com/rebus-org/Rebus/wiki/Outbox )**.
If you find any bug, then write about it, preferably in the form of a unit test and I will look at it.
