### ISSUE TITLE
Rebus.Kafka in .Net core Web API

### ISSUE THREAD

**Issue by hotamkushwah** [glazkovalex/Rebus.Kafka#5]
I am trying to use Rebus.Kafka in .Net core Web API. I tried to do by register it in startup.cs but it always throw "**The transport initialization procedure is still incomplete. There is no confirmation of completion of the subscription to the input queue**".

Code is like this :
services.AddRebus(configure => configure
                .Transport(t => t.UseKafka("localhost:9092", "MainQueue",producerConfig,consumerConfig))
                .Routing(r =>
                {
                    r.TypeBased()
                        .MapAssemblyOf<Message>(MainQueue)
                })

**Comment by zejji** [comment]
@hotamkushwah - Just to note that I had no problems with Rebus.Kafka up to version 1.4.3, but since then I get the same error as you. It may be worth comparing that version to see if it works; if so, it is presumably a bug in the more recent versions...

**Comment by hotamkushwah** [comment]
> @hotamkushwah - Just to note that I had no problems with Rebus.Kafka up to version 1.4.3, but since then I get the same error as you. It may be worth comparing that version to see if it works; if so, it is presumably a bug in the more recent versions...

I have checked with version 1.4.3 but still getting same error.  I have to use kafka as transport but due to this error not able to do it so now I am exploring the same with mass transit.

**Comment by hotamkushwah** [comment]
> Just to note that I had no problems with Rebus.Kafka up to version 1.4.3, but since then I get the same error as you. It may be worth comparing that version to see if it works; if so, it is presumably a bug in the more recent versions...

I have checked with version 1.4.3 but still getting same error.  I have to use kafka as transport but due to this error not able to do it so now I am exploring the same with mass transit.

**Comment by glazkovalex** [comment]
> I am trying to use Rebus.Kafka in .Net core Web API. I tried to do by register it in startup.cs but it always throw "**The transport initialization procedure is still incomplete. There is no confirmation of completion of the subscription to the input queue**".
> 
> Code is like this :
> services.AddRebus(configure => configure
> .Transport(t => t.UseKafka("localhost:9092", "MainQueue",producerConfig,consumerConfig))
> .Routing(r =>
> {
> r.TypeBased()
> .MapAssemblyOf(MainQueue)
> })

I will not be able to verify this error for the next 2 weeks.
Try using older versions of the package.

**Comment by hotamkushwah** [comment]
I have tried with older version up to 1.4.2 but getting same error.

**Comment by zejji** [comment]
@glazkovalex - Just to add that I had no issues with 1.4.3, but later versions have not worked for me.

**Comment by hotamkushwah** [comment]
>  Just to add that I had no issues with 1.4.3, but later versions have not worked for me.
@zejji 
Could you please share your startup configuration or your git hub repo link if possible.
Thanks in Advance.

**Comment by glazkovalex** [comment]
> I am trying to use Rebus.Kafka in .Net core Web API. I tried to do by register it in startup.cs but it always throw "**The transport initialization procedure is still incomplete. There is no confirmation of completion of the subscription to the input queue**".

@hotamkushwah, I wrote a [test to reproduce your case](https://github.com/glazkovalex/Rebus.Kafka/blob/master/Rebus.Kafka.Tests/SimpleTests.cs#L64), but without the WebAPI. I'm sure it doesn't matter in which application the bus is registered, in the console or WebAPI. [This test](https://github.com/glazkovalex/Rebus.Kafka/blob/master/Rebus.Kafka.Tests/SimpleTests.cs#L64) works correctly for me. You can see for yourself. To run the test, you must have Docker Desktop installed. 

You probably have something wrong with the infrastructure or with the Apahe Kafka instance. When sending a message, the transport checks whether the consumer's subscription to the queue has already completed initialization. If this subscription is not completed yet and does not complete in 30 seconds, then this exeption is returned. If in your case the consumer subscription takes longer than 30 seconds, then before the first sending to the bus, you can handle an exception with this message, and wait for the end of the subscription of your consumer to the queue in the loop. 

In the future, I will increase the wait time for initialization to complete to five minutes to make the transport more patient to wait for the consumer's queue subscription to complete.

**Comment by glazkovalex** [comment]
> I am trying to use Rebus.Kafka in .Net core Web API. I tried to do by register it in startup.cs but it always throw "**The transport initialization procedure is still incomplete. There is no confirmation of completion of the subscription to the input queue**".

@hotamkushwah, I wrote a [test to reproduce your case](https://github.com/glazkovalex/Rebus.Kafka/blob/master/Rebus.Kafka.Tests/SimpleTests.cs#L64), but without the WebAPI. I'm sure it doesn't matter in which application the bus is registered, in the console or WebAPI. [This test](https://github.com/glazkovalex/Rebus.Kafka/blob/master/Rebus.Kafka.Tests/SimpleTests.cs#L64) works correctly for me. You can see for yourself. To run the test, you must have Docker Desktop installed. 

You probably have something wrong with the infrastructure or with the Apahe Kafka instance. When sending a message, the transport checks whether the consumer's subscription to the queue has already completed initialization. If this subscription is not completed yet and does not complete in 30 seconds, then this exeption is returned. If in your case the consumer subscription takes longer than 30 seconds, then before the first sending to the bus, you can handle this exception, and wait for the end of the subscription of your consumer to the queue in the loop. 

Just in case, in the [new version 1.5.4](https://www.nuget.org/packages/Rebus.Kafka/1.5.4) I increase the wait time for initialization to complete to five minutes to make the transport more patient to wait for the consumer's queue subscription to complete. And also added to the recommendations for waiting for the end of the consumer's subscription to the queue in the message of this exception.

**Comment by glazkovalex** [comment]
@hotamkushwah, a similar question was discussed in the next topic [Usage of Confluent 1.5.3 causes topic creation issues](https://github.com/glazkovalex/Rebus.Kafka/issues/7). There, the problem was in a specific type of images with Apache Kafka, in particular in Strimzi, in which, on the strong recommendation of the community, automatic topics creation is DISABLED by default on the server side. Also, the Confluence.Kafka library, which is used in this Rebus.Kffka transport, since version 1.5.3 does not allow you to use the atomic creation of topics on some images with Apache Kafka, for example, Strimzi. 
At the same time, on the image "spotify/kafka", which is used in the test of this transport [Rubus.Kafka](https://github.com/glazkovalex/Rebus.Kafka), the automatic creation of topics works the same way with the old version of Confluence.Kafka. Therefore, I recommend that you either use a different version of the image for the Apache Kafka server, or use [old version of the package 1.4.3 Rebus. Kafka](https://www.nuget.org/packages/Rebus.Kafka/1.4.3) with the old version of Confluence. Kafka.
